[versions]
kotlin = "2.0.0-Beta2"
arrow = "2.0.0-SNAPSHOT"

[libraries]
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
